export const schools = [
    "Ashokegarh Adarsha Vidyalay For Boys",
    "Calcutta Public School",
    "Bagbazar Multipurpose Girls",
    "Sailendra Sircar Vidyalaya",
    "The Scottish Church Collegiate School, Goa Bagan",
    "La Martiniere For Boys",
    "La Martiniere For Girls",
    "Birla High School",
    "The Frank Anthony Public School",
    "Abhinav Bharti High School",
    "Don Bosco School",
    "Shri Shikshayatan School",
    "St. Xaviers Collegiate School",
    "Loreto Day School",
    "Pratt Memorial School",
    "Calcutta Girls' High School",
    "Bethune Collegiate Girls' High School",
    "Ashok Hall Girls Higher Secondary School",
    "Gokhale Memorial Girls School",
    "Sushila Birla Girls School",
    "Hindu School",
    "Hare School",
    "St. John's Diocesan Girls' Higher Secondary School, Sarat Bose Road",
    "Techno India Group Public School, Konnagar, Nabagram",
    "Delhi Public School, Howrah",
    "MCKV Liluah",
    "Guru Nanak",
    "Michael Nagar Siksha Niketan",
    "Rishi Aurobindo Memorial Academy",
    "St Stephen'S",
    "Dum Dum Sri Arabinda Vidyamandir For Boys",
    "Ramakrishna Mission, Baranagar",
    "Dum Dum Kishore Bharati High School",
    "IEM Public School",
    "Bidhannagar Govt High School",
    "Bidhannagar Municipal School",
    "Our Lady Queen Of The Missions School, Salt Lake",
    "Salt Lake School",
    "Bhavan's Gangbux Kanoria Vidyamandir",
    "Salt Lake Shiksha Niketan",
    "Hariyana Vidyamandir",
    "St. John's Public School",
    "Bodhicharya Senior Secondary School",
    "The Newtown School",
    "Delhi Public School, Newtown",
    "Orchids The International School",
    "Delhi Public School, Megacity",
    "Army Public School",
    "Mitra Institution",
    "National High School Boys",
    "South Point High School",
    "Delhi Public School, Ruby Park",
    "The New Horizon High School",
    "St. Lawrence High School",
    "South City International School",
    "Nava Nalanda Group Of Schools Kalighat",
    "Douglas Memorial High School",
    "Barasat Indira Gandhi Memorial High School",
    "Barasat P.C.S. Government High School",
    "Vivekananda Mission School, Joka",
    "MP Birla Foundation Higher Secondary School",
    "National Gems Higher Secondary School",
    "DAV Taratala",
    "Jodhpur Park Boys School",
    "St. Thomas Boys School",
    "Orient Day School",
    "Barisha High School",
    "P.B. Memorial School",
    "BDM International School",
    "Asian International School",
    "Gospel Home School",
]; 