import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Condensed, Freckle_Face, Fredoka, Sniglet, DM_Sans, Google_Sans_Flex } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import SquareGridBackground from "@/components/layout/SquareGridBackground";
import AudioVisualizer from "@/components/layout/AudioVisualizer";
import { AudioProvider } from "@/components/layout/AudioContext";
import OverlayBanner from "@/components/layout/OverlayBanner";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  display: "swap",
});

const freckleFace = Freckle_Face({
  variable: "--font-freckle-face",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  display: "swap",
});

const sniglet = Sniglet({
  variable: "--font-sniglet",
  weight: ["400", "800"],
  subsets: ["latin"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
});

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable} ${freckleFace.variable} ${fredoka.variable} ${sniglet.variable} ${dmSans.variable} ${googleSansFlex.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#ffede0]">
        <AudioProvider>
          <OverlayBanner />
          <Navbar />
          <SquareGridBackground />
          {children}
          <AudioVisualizer />
        </AudioProvider>
        <Footer/>
      </body>
    </html>
  );
}