import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import SquareGridBackground from "@/components/layout/SquareGridBackground";
import AudioVisualizer from "@/components/layout/AudioVisualizer";
import { AudioProvider } from "@/components/layout/AudioContext";
import OverlayBanner from "@/components/layout/OverlayBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#ffede0]">
        <AudioProvider>
          <OverlayBanner />
          <Navbar />
          <SquareGridBackground />
          {children}
          <AudioVisualizer />
        </AudioProvider>
      </body>
    </html>
  );
}